
const SAGAALLLIST = 'SAGAALLLIST';
const SAGABANNERLIST = 'SAGABANNERLIST';
const SAGARECOMMENDLIST = 'SAGARECOMMENDLIST';
const GET_BOTHACTION = 'GET_BOTHACTION';
const SAME_VALUE = 'SAME_VALUE';
const CALL_USEBACK = 'CALL_USEBACK';

export {
    SAGAALLLIST,
    SAGABANNERLIST,
    SAGARECOMMENDLIST,
    GET_BOTHACTION,
    SAME_VALUE,
    CALL_USEBACK
}